kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: {{ include "lldap.fullname" . }}-credentials
data:
  jwtSecret: {{ .Values.lldap.jwtSecret | b64enc }}
  ldapUserPass: {{ .Values.lldap.ldapUserPass | b64enc }}
  smtpPassword: {{ .Values.lldap.smtp.password | b64enc }}
